version: '3.8'

services:
  php-apache:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80" # ホストの8080をコンテナの80にマッピング
    volumes:
      - ./public:/var/www/html # ローカルのpublicディレクトリをコンテナ内にマウント
